### ISSUE TITLE
[BUG] - Responsive Issue on Event Page for Non-Mobile Viewports

### ISSUE THREAD

**Issue by ghanshyam2005singh** [DEVRhylme-Foundation/new-website#41]
### Describe the bug

There is a responsive issue on the Event Page when the window is resized to a width greater than mobile size (e.g., tablet view or small desktop screens). The layout does not adjust properly, causing visual inconsistencies.

### To Reproduce

1. Open the Event Page in a web browser.
2. Resize the browser window to a size between 600px and 1024px width (greater than mobile but smaller than standard desktop screens).
3. Observe the layout of the page, especially in the Filters section and Event cards grid.

### Expected behavior

The page should adjust gracefully to fit non-mobile viewports, with content aligned and readable, maintaining proper spacing and alignment.

### Add Screenshots or Recordings

![Screenshot 2024-11-26 211801](https://github.com/user-attachments/assets/299485c6-2ed3-4ef8-a65a-22b487046cd1)

**Comment by MAVRICK-1** [comment]
@AishwaryJain07 sorry has already been solved. Keep an eye on this repository for the upcoming issues
