### ISSUE TITLE
[FEATURE] Update_FeatureSection_For_Dark_Mode

### ISSUE THREAD

**Issue by asteriskayush007** [DEVRhylme-Foundation/new-website#57]
### Feature title

#Update_FeatureSection_For_Dark_Mode

### Motivation

##Our CTO And Web Dev Lead Suggest me to Improve that bug

### Alternatives

Uploading Screen Recording 2024-12-10 at 9.53.45 PM.mov…

**Comment by Pal-prakash2** [comment]
Can you assign this bug to me ? will look into this

**Comment by MAVRICK-1** [comment]
@Pal-prakash2  is the issue is already solved by @asteriskayush007  , he will raise the PR by today
